body:
  - type: input
    attributes:
      name: input_cur
      label: "Default input currency:"
      defaultValue: "USD"
      description: "Default source currency (ISO 4217)"
  - type: input
    attributes:
      name: output_cur
      label: "Default output currency:"
      defaultValue: "USD EUR JPY"
      description: "Default output currency (ISO 4217; whitespace-separated)"
  - type: input
    attributes:
      name: app_id
      label: "OpenExchangeRates App ID:"
      defaultValue: ""
      description: "OpenExchangeRates App ID (used if cache fails)"
  - type: dropdown
    attributes:
      name: update_freq
      label: "Update Frequency:"
      defaultValue: "daily"
      options:
        - never
        - hourly
        - daily
      description: "Update frequency (auto-refresh rates)"
  - type: input
    attributes:
      name: separators
      label: "Separator:"
      defaultValue: "to in : ."
      description: "Source⇄destination separators (whitespace-separated)"
  - type: input
    attributes:
      name: destination_separators
      label: "Destination Separator:"
      defaultValue: "and & ,"
      description: "Destination currency separators (whitespace-separated)"
  - type: textarea
    attributes:
      name: aliases
      label: "Aliases:"
      defaultValue: "USD = $ dollar dollars bucks\nEUR = euro euros"
      description: "Currency aliases (whitespace-separated)"