name: Publish

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      python_ver: 3.8
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ env.python_ver }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.python_ver }}
    - name: get version
      id: version
      uses: notiz-dev/github-action-json-property@release
      with:
        path: 'plugin.json'
        prop_path: 'Version'
    - run: echo ${{steps.version.outputs.prop}}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./requirements.txt -t ./lib
        zip -r CurrencyPP.zip . -x '*.git*'
    - name: Publish
      if: success()
      uses: softprops/action-gh-release@v1
      with:
        files: 'CurrencyPP.zip'
        tag_name: "v${{steps.version.outputs.prop}}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}